; Inno Setup script - installer for IrrigationControlApp
; Usage: compile with Inno Setup Compiler (ISCC.exe)
; Example compile:
; ISCC.exe /DMyAppExe="C:\WEBtg\univer\irrigation-control-system\dist\IrrigationControlApp.exe" installer.iss

[Setup]
AppName=Irrigation Control
AppVersion=1.1
; Install for all users (Program Files)
DefaultDirName={pf}\IrrigationControl
DefaultGroupName=Irrigation Control
OutputBaseFilename=IrrigationControlInstaller
Compression=lzma
SolidCompression=yes
PrivilegesRequired=admin
LicenseFile=EULA.txt
SetupIconFile=icon.ico

[Files]
; EXE generated by PyInstaller (define MyAppExe when compiling or replace with full path)
Source: "{#MyAppExe}"; DestDir: "{app}"; Flags: ignoreversion
; include EULA and optional icon
Source: "EULA.txt"; DestDir: "{app}"; Flags: dontcopy
; If you have an ICO file, include it here and the SetupIconFile above should point to it
; Source: "icon.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\Irrigation Control"; Filename: "{app}\IrrigationControlApp.exe"
Name: "{userdesktop}\Irrigation Control"; Filename: "{app}\IrrigationControlApp.exe"; Tasks: desktopicon

[Tasks]
Name: desktopicon; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"; Flags: unchecked

[Run]
Filename: "{app}\IrrigationControlApp.exe"; Description: "Launch Irrigation Control"; Flags: nowait postinstall skipifsilent
